export const formItems = [
    { field: 'title',
      type: 'input',
      label: '商品名称',
      placeholder: '请输入商品名称'
    },
    { 
      field: 'catName',
      type: 'select',
      label: '类目',
      placeholder: '请选择商品类目',
      options: [
        { title: '手机数码', value: '手机数码' },
        { title: '食品', value: '食品' },
        { title: '生鲜', value: '生鲜' },
        { title: '洗护', value: '洗护' },
        { title: '美妆', value: '美妆' },
        { title: '母婴', value: '母婴' },
        { title: '百货', value: '百货' },
        { title: '女鞋', value: '女鞋' },
        { title: '保健', value: '保健' },
        { title: '女装', value: '女装' },
        { title: '饰品', value: '饰品' },
        { title: '电器', value: '电器' },
        { title: '内衣', value: '内衣' },
        { title: '家装', value: '家装' },
        { title: '箱包', value: '箱包' },
        { title: '珠宝', value: '珠宝' },
        { title: '运动', value: '运动' },
        { title: '男鞋', value: '男鞋' },
        { title: '车品', value: '车品' },
        { title: '企业', value: '企业' },
        { title: '宠物', value: '宠物' },
        { title: '其他', value: '其他' },
      ]
    },
    { field1: 'min',
      field2: 'max',
      type: 'countpicker',
      label: '销售数量',
      placeholder1: '最小数',
      placeholder2: '最大数',
    },
]
